//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Talent_Addmission_System.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string dataSourcePath {
            get {
                return ((string)(this["dataSourcePath"]));
            }
            set {
                this["dataSourcePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("students_table")]
        public string accessTableName {
            get {
                return ((string)(this["accessTableName"]));
            }
            set {
                this["accessTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string imagesLocation {
            get {
                return ((string)(this["imagesLocation"]));
            }
            set {
                this["imagesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingsState {
            get {
                return ((bool)(this["settingsState"]));
            }
            set {
                this["settingsState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Windows 10</string>
  <string>Windows 11</string>
  <string>MacOS</string>
  <string>MS Word 2022</string>
  <string>MS Excel 2022                             </string>
  <string>MS Access 2022</string>
  <string>MS PowerPoint 2022</string>
  <string>Office Package</string>
  <string>Adobe Photoshop Basics</string>
  <string>Adobe Photoshop Retouching</string>
  <string>Adobe Photoshop Designing</string>
  <string>Adobe Premier</string>
  <string>Adobe After Effect</string>
  <string>Adobe Illustrator</string>
  <string>C Language</string>
  <string>C++</string>
  <string>OOP</string>
  <string>C#</string>
  <string>Java</string>
  <string>Python</string>
  <string>Kotlin</string>
  <string>Android Application developement</string>
  <string>HTML</string>
  <string>CSS</string>
  <string>JavaScript</string>
  <string>Todays Need</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection programsList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["programsList"]));
            }
            set {
                this["programsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12345")]
        public string password {
            get {
                return ((string)(this["password"]));
            }
            set {
                this["password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XXXXX-XXXXX-XXXXX-XXXXX-XXXXX")]
        public string activationCode {
            get {
                return ((string)(this["activationCode"]));
            }
            set {
                this["activationCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Abu Talib Road, Gali French Bakery, Quetta")]
        public string courseAddress {
            get {
                return ((string)(this["courseAddress"]));
            }
            set {
                this["courseAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+92 313 1454166")]
        public string contactNumber {
            get {
                return ((string)(this["contactNumber"]));
            }
            set {
                this["contactNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool adminLogin {
            get {
                return ((bool)(this["adminLogin"]));
            }
            set {
                this["adminLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12345")]
        public string userPassword {
            get {
                return ((string)(this["userPassword"]));
            }
            set {
                this["userPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("payments_table")]
        public string paymentTable {
            get {
                return ((string)(this["paymentTable"]));
            }
            set {
                this["paymentTable"] = value;
            }
        }
    }
}
